import { NextResponse } from 'next/server';
import { LogKind, LogStatus } from '@prisma/client';
import { recordActivity } from '@/lib/activity';
import { getRelevantKnowledge } from '@/lib/knowledgeRetrieval';
import { FALLBACK_SPOKEN_REPLY, buildSystemPrompt, describeSources } from '@/lib/knowledgePrompt';
import { LlmError, generateAnswer, llmModel, type ChatTurn } from '@/lib/llm';

/**
 * The avatar's brain.
 *
 * Knowledge comes from Postgres, retrieved per question; the answer is generated by the
 * local Qwen3 model in the `ollama` container. Nothing here imports
 * `app/constants/knowledge.ts`, and no external API or API key is involved — an entry
 * added in the admin console is used on the very next question, with no rebuild.
 */

/** Turns kept as conversational context. Older turns fall out of the window. */
const MAX_HISTORY_TURNS = 10;
const MAX_MESSAGE_CHARS = 2_000;

// Retrieval is what keeps request size flat as the knowledge base grows: only these many
// records reach the model, never the whole table.
const KNOWLEDGE_LIMIT = 6;
const KNOWLEDGE_MAX_CHARS = 6_000;

export const dynamic = 'force-dynamic';

function parseHistory(value: unknown): ChatTurn[] {
  if (!Array.isArray(value)) return [];

  return value
    .filter((turn): turn is ChatTurn => {
      if (typeof turn !== 'object' || turn === null) return false;
      const { role, content } = turn as Record<string, unknown>;
      return (role === 'user' || role === 'assistant') && typeof content === 'string' && Boolean(content.trim());
    })
    .slice(-MAX_HISTORY_TURNS)
    .map((turn) => ({ role: turn.role, content: turn.content.slice(0, MAX_MESSAGE_CHARS) }));
}

export async function POST(request: Request) {
  let body: Record<string, unknown>;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
  }

  const rawMessage = body.message;
  if (typeof rawMessage !== 'string' || !rawMessage.trim()) {
    return NextResponse.json({ error: 'message is required' }, { status: 400 });
  }

  const message = rawMessage.trim().slice(0, MAX_MESSAGE_CHARS);
  const history = parseHistory(body.history);
  // Optional: lets a turn be traced back to the conversation it belongs to in the logs.
  const sessionId = typeof body.sessionId === 'string' ? body.sessionId.slice(0, 200) : null;

  // A retrieval outage must not silence the avatar — it answers without grounding and
  // says so, rather than failing the request outright.
  let knowledge: Awaited<ReturnType<typeof getRelevantKnowledge>> = [];
  const retrievalStartedAt = Date.now();
  try {
    knowledge = await getRelevantKnowledge(message, {
      limit: KNOWLEDGE_LIMIT,
      maxChars: KNOWLEDGE_MAX_CHARS,
    });
  } catch (err) {
    console.error('[chat] knowledge retrieval failed', err);
  }
  const retrievalMs = Date.now() - retrievalStartedAt;

  const systemPrompt = buildSystemPrompt(knowledge);
  const startedAt = Date.now();

  try {
    const { text, model, tokensIn, tokensOut } = await generateAnswer(
      systemPrompt,
      history,
      message
    );

    const latencyMs = Date.now() - startedAt;
    const response = text || FALLBACK_SPOKEN_REPLY;

    await recordActivity({
      event: message.slice(0, 120),
      kind: LogKind.CHAT,
      sessionId,
      model,
      latencyMs,
      tokensIn,
      tokensOut,
      detail: `${knowledge.length} knowledge record(s), retrieval ${retrievalMs}ms`,
    });

    // `response` is unchanged from the original contract; `sources` is additive.
    return NextResponse.json({ response, sources: describeSources(knowledge) });
  } catch (err) {
    const failure =
      err instanceof LlmError
        ? err
        : new LlmError('Generation failed', 'upstream_error', String(err));

    // Printed to the server terminal as well as stored, so a misconfiguration is visible
    // where the developer is already looking instead of only in the activity log.
    console.error(`[chat] ${failure.code}: ${failure.message}`, failure.detail ?? '');

    await recordActivity({
      event: 'Local model request failed',
      kind: LogKind.CHAT,
      status: LogStatus.ERROR,
      sessionId,
      model: llmModel(),
      latencyMs: Date.now() - startedAt,
      detail: `${failure.code}: ${failure.message}`,
    });

    // A model that is missing or down is a configuration fault on this machine, not a bad
    // question, and the message says exactly what to do about it.
    return NextResponse.json(
      { error: failure.message, code: failure.code },
      { status: failure.code === 'upstream_error' ? 502 : 500 }
    );
  }
}
